export const CardsArray  = [
  { figure: "NUMBER", value: 1, seed:'BASTONI',url: require('../assets/cards/helmet1')},
  { figure: "NUMBER", value: 2, seed:'BASTONI',url: require('../assets/cards/helmet2') },
  { figure: "NUMBER", value: 3, seed:'BASTONI',url: require('../assets/cards/helmet3') },
  { figure: "NUMBER", value: 4, seed:'BASTONI',url: require('../assets/cards/helmet4') },
  { figure: "NUMBER", value: 5, seed:'BASTONI',url: require('../assets/cards/helmet5') },
  { figure: "NUMBER", value: 6, seed:'BASTONI',url: require('../assets/cards/helmet6') },
  { figure: "NUMBER", value: 7, seed:'BASTONI',url: require('../assets/cards/helmet7') },
  { figure: "FANTE", value: 0.5, seed:'BASTONI',url: require('../assets/cards/helmet8') },
  { figure: "CAVALLO", value: 0.5, seed:'BASTONI',url: require('../assets/cards/helmet9') },
  { figure: "RE", value: 0.5, seed:'BASTONI',url: require('../assets/cards/helmet10') },
  { figure: "NUMBER", value: 1, seed:'DENARI',url: require('../assets/cards/axe1')},
  { figure: "NUMBER", value: 2, seed:'DENARI',url: require('../assets/cards/axe2') },
  { figure: "NUMBER", value: 3, seed:'DENARI',url: require('../assets/cards/axe3') },
  { figure: "NUMBER", value: 4, seed:'DENARI',url: require('../assets/cards/axe4') },
  { figure: "NUMBER", value: 5, seed:'DENARI',url: require('../assets/cards/axe5') },
  { figure: "NUMBER", value: 6, seed:'DENARI',url: require('../assets/cards/axe6') },
  { figure: "NUMBER", value: 7, seed:'DENARI',url: require('../assets/cards/axe7') },
  { figure: "FANTE", value: 0.5, seed:'DENARI',url: require('../assets/cards/axe8') },
  { figure: "CAVALLO", value: 0.5, seed:'DENARI',url: require('../assets/cards/axe9') },
  { figure: "RE", value: 0.5, seed:'DENARI',url: require('../assets/cards/axe10') },
  { figure: "NUMBER", value: 1, seed:'SPADE',url: require('../assets/cards/sword1')},
  { figure: "NUMBER", value: 2, seed:'SPADE',url: require('../assets/cards/sword2') },
  { figure: "NUMBER", value: 3, seed:'SPADE',url: require('../assets/cards/sword3') },
  { figure: "NUMBER", value: 4, seed:'SPADE',url: require('../assets/cards/sword4') },
  { figure: "NUMBER", value: 5, seed:'SPADE',url: require('../assets/cards/sword5') },
  { figure: "NUMBER", value: 6, seed:'SPADE',url: require('../assets/cards/sword6') },
  { figure: "NUMBER", value: 7, seed:'SPADE',url: require('../assets/cards/sword7') },
  { figure: "FANTE", value: 0.5, seed:'SPADE',url: require('../assets/cards/sword8') },
  { figure: "CAVALLO", value: 0.5, seed:'SPADE',url: require('../assets/cards/sword9') },
  { figure: "RE", value: 0.5, seed:'SPADE',url: require('../assets/cards/sword10') },
  { figure: "NUMBER", value: 1, seed:'COPPE',url: require('../assets/cards/shield1')},
  { figure: "NUMBER", value: 2, seed:'COPPE',url: require('../assets/cards/shield2')},
  { figure: "NUMBER", value: 3, seed:'COPPE',url: require('../assets/cards/shield3')},
  { figure: "NUMBER", value: 4, seed:'COPPE',url: require('../assets/cards/shield4')},
  { figure: "NUMBER", value: 5, seed:'COPPE',url: require('../assets/cards/shield5')},
  { figure: "NUMBER", value: 6, seed:'COPPE',url: require('../assets/cards/shield6')},
  { figure: "NUMBER", value: 7, seed:'COPPE',url: require('../assets/cards/shield7')},
  { figure: "FANTE", value: 0.5, seed:'COPPE',url: require('../assets/cards/shield8')},
  { figure: "CAVALLO", value: 0.5, seed:'COPPE',url: require('../assets/cards/shield9')},
  { figure: "RE", value: 0.5, seed:'COPPE',url: require('../assets/cards/shield10')},
];
